export enum Status {
  POSTED = 'POSTED',
  PENDING = 'PENDING',
  PAYMENT_CONFIRM = 'PAYMENT_CONFIRM',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  WAITING = 'WAITING',
}
